on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build code
      run: |
        # Add your build commands here

    - name: Test code
      run: |
        # Add your test commands here

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to production
      run: |
        # Add deployment commands here
